### ISSUE TITLE
move to YAML for template specifiers

### ISSUE THREAD

**Issue by jabooth** [menpo/landmarkerio-server#9]

**Comment by lirsacc** [comment]
@jabooth Is maintaining the order of keys as specified in the file important ? As order should not matter in yaml files order is not guaranteed by the PyYAML parser but it could be handled  if needed.

Otherwise previous commits parses templates like :

```
mouth:
  points: 6
nose:
  points: 3
  connectivity:
    - 0 1
    - 1 2
left_eye:
  points: 8
  connectivity:
    - 0:7
    - 7 0
right_eye:
  points: 8
  connectivity: cycle
chin: 1
```

to the same json as the text files (without the same order)

**Comment by jabooth** [comment]
@lirsacc Unfortunately order is important - this is because landmarks can always be interpreted as a single large (ordered) point collection, or single ordered groups.

I believe we moved the an array in LJSON format 2 from keys so we had a guarantee of maintaining key order. Perhaps we should use an array in YAML template too to definite the different groups?

**Comment by lirsacc** [comment]
Yep, simple array should work with something like:

```
groups:
  - label: mouth
    points: 6
  - label: nose
    points: 3
    connectivity:
      - 0 1
      - 1 2
  - label: left_eye
    points: 8
    connectivity:
      - 0:7
      - 7 0
  - label: right_eye
    points: 8
    connectivity: cycle
  - label: chin
    points: 1
```

Would also make it simpler to add metadata aside the actual template (ignored now but tracking an update date to compare with ljson file could have it's use for versioning schemas)

I have updated my branch and it consistently gives the same json output as the old text file.
